language: minimal
services:
- docker
addons:
  apt:
    update: true
    packages:
    - curl
    - openssl
    - ca-certificates
    - make
    - qemu-user-static
env:
  global:
    - PARALLELMFLAGS="-j4"
    - PORTABLE_WORSPACE=1
  matrix:
    - DISTRO=ubuntu BUILDTYPE=Debug      MARCH=amd64   CHECK_TARGET=memcheck
    - DISTRO=ubuntu BUILDTYPE=Coverage   MARCH=amd64   CHECK_TARGET=check
    - DISTRO=ubuntu BUILDTYPE=Release    MARCH=amd64   CHECK_TARGET=memcheck
    - DISTRO=ubuntu BUILDTYPE=Debug      MARCH=arm32v7 CHECK_TARGET=check
    - DISTRO=ubuntu BUILDTYPE=MinSizeRel MARCH=arm32v7 CHECK_TARGET=check
    - DISTRO=alpine BUILDTYPE=Debug      MARCH=amd64   CHECK_TARGET=check
before_script:
- make BUILDTYPE=$BUILDTYPE MARCH=$MARCH
script:
- make DISTRO=$DISTRO BUILDTYPE=$BUILDTYPE MARCH=$MARCH $CHECK_TARGET
after_success:
- bash <(curl -s https://codecov.io/bash)
