language: minimal
services:
- docker
addons:
  apt:
    update: true
before_install:
- sudo apt-get install -y curl openssl ca-certificates
- sudo apt-get install -y make
- sudo apt-get install -y qemu-user-static
env:
  global:
    - MAKEFLAGS="-j 2"
  matrix:
    - MARCH=amd64
    - MARCH=arm32v7
before_script:
- make MARCH=$MARCH
script:
- make check MARCH=$MARCH
