language: cpp

compiler:
  - gcc

before_install:
  - mkdir -p .deps
  - cd .deps
  - wget https://github.com/libfuse/libfuse/archive/fuse-3.1.1.tar.gz
  - tar -xf fuse-3.1.1.tar.gz
  - cd libfuse-fuse-3.1.1
  - ./makeconf.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - wget https://github.com/warmcat/libwebsockets/archive/v3.1.0.tar.gz
  - tar -xf v3.1.0.tar.gz
  - cd libwebsockets-3.1.0
  - mkdir .build
  - cd .build
  - cmake ..
  - make
  - sudo make install
  - cd ..
  - cd ..
  - cd ..

before_script:
  - mkdir .build
  - cd .build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - make
