language: cpp

compiler:
  - gcc

before_install:
  - mkdir -p .deps
  - cd .deps
  - wget -O fuse-3.1.1.tar.gz https://github.com/libfuse/libfuse/archive/fuse-3.1.1.tar.gz
  - tar -xf fuse-3.1.1.tar.gz
  - cd libfuse-fuse-3.1.1
  - ./makeconf.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - wget -O libwebsockets-3.1.0.tar.gz https://github.com/warmcat/libwebsockets/archive/v3.1.0.tar.gz
  - tar -xf libwebsockets-3.1.0.tar.gz
  - cd libwebsockets-3.1.0
  - mkdir .build
  - cd .build
  - cmake ..
  - make
  - sudo make install
  - cd ..
  - cd ..
  - wget -O libjansson-2.12.tar.gz https://github.com/akheron/jansson/archive/v2.12.tar.gz
  - tar -xf libjansson-2.12.tar.gz
  - cd jansson-2.12
  - mkdir .build
  - cd .build
  - cmake ..
  - make
  - sudo make install
  - cd ..
  - cd ..
  - wget -O gtest-1.8.1.tar.gz https://github.com/google/googletest/archive/release-1.8.1.tar.gz
  - tar -xf gtest-1.8.1.tar.gz
  - cd googletest-release-1.8.1
  - mkdir .build
  - cd .build
  - cmake ..
  - make
  - sudo make install
  - cd ..
  - cd ..
  - cd ..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib


before_script:
  - mkdir .build
  - cd .build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_TESTS=ON ..

script:
  - make
  - ./alltests
