language: cpp

compiler:
  - gcc

before_install:
  - wget https://github.com/libfuse/libfuse/archive/fuse-3.1.1.tar.gz
  - tar -xf fuse-3.1.1.tar.gz
  - cd libfuse-fuse-3.1.1
  - ./makeconf.sh
  - ./configure
  - make
  - sudo make install

before_script:
  - mkdir .build
  - cd .build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - make
